apiVersion: v1
kind: Service
metadata:
  name: resulting-service
  labels:
    name: resulting-service
    app: voting-app
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: 
    name: resultapp-pod
    app: voting-app
