apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    app: voting-app
spec:
  containers:
      - name: voting-app-container
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
