apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica-app
  labels:
    app: myrep-app
    type: front-end

spec:
  template:
    metadata:
      name: mypod-app
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: ngnix-container
          image: nginx

  replicas: 3
